### ISSUE TITLE
Программа не работает

### ISSUE THREAD

**Issue by DamianMorozov** [OnlyFart/EbookConverter#1]
Бинарников и релизов нет.
.NET Core 3.1 уже устарел.
После самостоятельного обновления на .NET 7 и Nuget-пакетов, выдает ошибку сборки.
![image](https://user-images.githubusercontent.com/13628284/213541043-b56b43c0-168c-4b3f-a80e-6cf469f362f2.png)

**Comment by OnlyFart** [comment]
Перевел на .net 7,  добавил релизы

**Comment by DamianMorozov** [comment]
Сборка выполнена успешно.
Скачал и установил `wkhtmltox-0.12.6-1.msvc2015-win64.exe`.
Но получаю ошибку `Fail convert Temp1\file1.epub to Temp2\file1.pdf. Message An error occurred trying to start process 'wkhtmltopdf' with working directory 'C:\Temp\EbookConverter'. The system cannot find the file specified.
Fail convert Temp1\file2.fb2 to Temp2\file2.pdf. Message FB2Library.Elements.Table.TableItem`.
![image](https://user-images.githubusercontent.com/13628284/222729106-9316365f-e171-4574-a98a-c6cc85199255.png)

**Comment by DamianMorozov** [comment]
appsettings.json
```
{
    "GlobalConfig": {
        "HtmlPatternsConfig": {
            "CoverPath": "Patterns/cover.html",
            "ContentPath": "Patterns/content.html"
        },
        "WkhtmltopdfConfig": {
            "DefaultArgs": "--enable-local-file-access --image-quality 100 --zoom 1.3 --javascript-delay 10000 -B 25mm -L 25mm -R 25mm -T 25mm --viewport-size 1280x1024",
            "Path": "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
        },
        "ProcessorConfig": {
            "MaxParallelThreads": 10
        }
    }
}
```

C:\Temp\EbookConverter>EbookConverter.exe -s "C:\Temp\EbookConverter\Temp1" -d "C:\Temp\EbookConverter\Temp2"
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'EbookConverter.Program' threw an exception.
 ---> System.IO.InvalidDataException: Failed to load configuration from file 'C:\Temp\EbookConverter\appsettings.json'.
 ---> System.FormatException: Could not parse the JSON file.
 ---> System.Text.Json.JsonReaderException: 'P' is an invalid escapable character within a JSON string. The string should be correctly escaped. LineNumber: 8 | BytePositionInLine: 24.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
   at System.Text.Json.Utf8JsonReader.ConsumeString()
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at EbookConverter.IoC.EpubConverterNinject.Load() in ```

**Comment by OnlyFart** [comment]
> appsettings.json
> 
> ```
> {
>     "GlobalConfig": {
>         "HtmlPatternsConfig": {
>             "CoverPath": "Patterns/cover.html",
>             "ContentPath": "Patterns/content.html"
>         },
>         "WkhtmltopdfConfig": {
>             "DefaultArgs": "--enable-local-file-access --image-quality 100 --zoom 1.3 --javascript-delay 10000 -B 25mm -L 25mm -R 25mm -T 25mm --viewport-size 1280x1024",
>             "Path": "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
>         },
>         "ProcessorConfig": {
>             "MaxParallelThreads": 10
>         }
>     }
> }
> ```
> 
> C:\Temp\EbookConverter>EbookConverter.exe -s "C:\Temp\EbookConverter\Temp1" -d "C:\Temp\EbookConverter\Temp2"
> 
> ```
> Unhandled exception. System.TypeInitializationException: The type initializer for 'EbookConverter.Program' threw an exception.
>  ---> System.IO.InvalidDataException: Failed to load configuration from file 'C:\Temp\EbookConverter\appsettings.json'.
>  ---> System.FormatException: Could not parse the JSON file.
>  ---> System.Text.Json.JsonReaderException: 'P' is an invalid escapable character within a JSON string. The string should be correctly escaped. LineNumber: 8 | BytePositionInLine: 24.
>    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
>    at System.Text.Json.Utf8JsonReader.ConsumeStringAndValidate(ReadOnlySpan`1 data, Int32 idx)
>    at System.Text.Json.Utf8JsonReader.ConsumeString()
>    at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
>    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
>    at System.Text.Json.Utf8JsonReader.Read()
>    at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
>    at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
>    at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
>    at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
>    at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
>    at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
>    at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
>    --- End of inner exception stack trace ---
>    at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
>    --- End of inner exception stack trace ---
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
>    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
>    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>    at EbookConverter.IoC.EpubConverterNinject.Load() in ```
> ```

Обратный слеш в json конфигах надо экранировать еще одним обратным слешем. Должно быть как то так
"Path": "C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe"

**Comment by DamianMorozov** [comment]
Ошибка конвертирования fb2.
```
C:\Temp\EbookConverter>EbookConverter.exe -s "Temp1" -d "Temp2"
Start convert Temp1\Arrays and Time Complexity Implementation Solutions in C#.epub to Temp2\Arrays and Time Complexity Implementation Solutions in C#.pdf
Start convert Temp1\Восстановление данных.fb2 to Temp2\Восстановление данных.pdf
Fail convert Temp1\Восстановление данных.fb2 to Temp2\Восстановление данных.pdf. Message FB2Library.Elements.Table.TableItem
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Success convert Temp1\Arrays and Time Complexity Implementation Solutions in C#.epub to Temp2\Arrays and Time Complexity Implementation Solutions in C#.pdf
```
✓ `epub → pdf`
x `fb2 → pdf`

**Comment by OnlyFart** [comment]
Нужен файлик, чтобы понять, что не так

**Comment by DamianMorozov** [comment]
Вот нашёл такой файл [fb2](https://knigism.online/downloadbook/140536).

**Comment by OnlyFart** [comment]
Доработал.

**Comment by DamianMorozov** [comment]
Прекрасная работа! То, что нужно.
✓ epub → pdf
✓ fb2 → pdf
```
C:\Temp\EbookConverter>EbookConverter.exe -s "Temp1" -d "Temp2"
Start convert Temp1\Test.fb2 to Temp2\Test.pdf
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Success convert Temp1\Test.fb2 to Temp2\Test.pdf
```

**Comment by DamianMorozov** [comment]
Исходный код обновлён. Сборка проекта без ошибок.
Ручные тесты пройдены. Конверт файлов без ошибок.
Спасибо.
